image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 12

primary:
  initdb:
    scriptsSecret: 'postgres-initdb-scripts'
  persistence:
    enabled: False
  extendedConfiguration: |
    max_connections = 400
    shared_buffers = 1024MB
  resources:
    limits:
      memory: "8Gi"
      cpu: "2"
    requests:
      memory: "4Gi"
      cpu: "500m"
  nodeSelector:
    kubernetes.io/hostname: stashcache.t2.ucsd.edu  
  tolerations:
    - key: "nautilus.io/stashcache"
      operator: "Exists"
      effect: "NoSchedule"

