image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 12

primary:
  initdb:
    scriptsSecret: 'postgres-initdb-scripts'
  persistence:
    enabled: True
    size: 16Gi
  extendedConfiguration: |
    max_connections = 400
    shared_buffers = 1024MB
  resources:
    limits:
      memory: "8Gi"
      cpu: "2"
    requests:
      memory: "4Gi"
      cpu: "500m"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nautilus.io/rack
              operator: In
              values:
                - "AA36"
